### ISSUE TITLE
Data history no longer works

### ISSUE THREAD

**Issue by nofear77** [produdegr/homebridge-3em-energy-meter#1]
[
![IMG_2130](https://user-images.githubusercontent.com/62308854/114449202-c5de8a00-9bd4-11eb-84e5-815739030f61.jpeg)
![IMG_2131](https://user-images.githubusercontent.com/62308854/114449228-cecf5b80-9bd4-11eb-90e3-ef7f73e45f10.jpeg)

](url)

**Comment by produdegr** [comment]
This is a known limitation of the fakegato-history plugin that emulates an EVE device. After a finite amount of data, the datafile is not rolled over so that the history is stuck. Fake-gato developer states as "TODO:  Support for rolling-over of the history", so it is something that will be fixed sometime hopefully.
The solution is to simply rename or delete the persistend file that holds the fake-gato history. The relevant file is usually found in your homebridge folder "/var/lib/homebridge" and is called "homebridge_Energy Meter_persist.json".
If this file is in this location and the home bridge accessory is called "Energy Meter" (as you have it) you can type:
sudo rm "/var/lib/homebridge/homebridge_Energy Meter_persist.json" 
to remove the file. After restarting homebridge will fake-gato start to work again and populate a new file, thus showing data in the graph.
This happens with all homebridge plugins that use the fake-gato plugin.

**Comment by nofear77** [comment]
I tried deleting just the file, that didn't work, I had to reinstall the entire plugin. Now it works again, I hope the error will be fixed soon. Thanks for your good job.

**Comment by produdegr** [comment]
Problem is out of my hands.

**Comment by wasnertobias** [comment]
So I have changed hardware (same SD card, different RaspberryPi) and ran into the same issue.

I have tried to delete the file mentioned above (**it was empty**)
> sudo rm "/var/lib/homebridge/homebridge_Energy Meter_persist.json"

I have also tried to re-install the plugin. I do not seem to get it to work once again. Also other plugins - which also use the fake-gate plugin - do/did not (ever) cause any issues for me. The other plugins also most likely produce less data than this plugin, so it can be a rollover-issue as mentioned above and it was only a coincidence that I switched over to new hardware just in this moment.

For me it would be absolutely sufficient to not keep any old data and just to show the most recent one, probably I can come up with a cleanup cronjob if I could find out which file to delete...

@produdegr Would you have any advice on how I could further debug or get it to work again?

**Comment by produdegr** [comment]
Did not see this problem for a long time now. I personally installed Homebridge from their ready made images you can download.
On these images I never had this issue again for the last 1 1/2 year now.
If the persistent file did not work, then I would do a "Remove Single Cached Accessory" in the homebridge UI settings  and select my plugin, also uninstall it. Then a reboot, then re-install.
If this does not help you could try the above solution of re-installing homebridge from an SD image (but you will have the hustle to install everything again).
